### PR TITLE
Version 2.1.0

### PR DESCRIPTION
**Pull request by nobodyczcz**
Version 2.1.0 - 2024-11-15
----------------------------
Added:
- Added `new_tasks` API to `SharedEnvironment` to notify the entry of new tasks released at the current timestep.
- Added `new_freeagents` API to `SharedEnvironment` to notify the entry of new free robots, who newly completed their assigned task, at the current timestep.
- Added `--logDetailLevel` option to specify the level of details of the log file.

Changes:
- API `vector<Task> task_pool` in `SharedEnvironment` is now removed. Use `unordered_map<int, Task> task_pool` instead, which uses `task_id` as the key.
- Documentation updated to reflect the changes in the API.
- The competition system now waits for entry to return and records the number of timeouts, then progress to the simulator. This prevents the entry using the unrecorded time spent on the simulator.
- Output JSON records a number of entry timeouts, invalid schedules, and invalid actions.
- Default Scheduler now uses the new API to schedule tasks.
- The `update_goal_locations` function in Default Entry is updated to use the new `task_pool` API. (Warning, when updating your entry, make sure you review the changes on `Entry.cpp` and decide how you adapt the changes to your entry implementation.)
- Update the Python binding to support the updated API.
- Updated the example python scheduler to use the new API. (Warning, when updating, make sure you review the changes on `pyTaskScheduler.py` and decide how you adapt the changes to your scheduler implementation.)

### CODE REVIEW

**Comment by nobodyczcz** [comment]
Add additional inline documentation to all functions and classes that participants may need to read through.
- At the top of each function, explain what each function does and how to interpret parameters and return values.
- Inside the function, explain what each code block does.

@YueZhang-studyuse  @HanZhang39

**Comment by nobodyczcz** [comment]
Start-kit parameters:

- fileStoragePath is an optional parameter, if not specified, will read from environment variable $LORR_LARGE_FILE_STORAGE_PATH, if specified we ignore the environment variable.
- document the above behaviour in `INPUT_OUTPUT_FORMAT.md`.

**Comment by nobodyczcz** [comment]
Bring updated cli help info into the documentation.

**Comment by YueZhang-studyuse** [comment]
@nobodyczcz I can't see docstrings in Entry.cpp, have you pushed changes or is it in other branches?

**Pull request merged**
